is_palindrome:
	@g++ -g -o neetcode_Q1/is_palindrome neetcode_Q1/is_palindrome.cpp
	@./neetcode_Q1/is_palindrome

contains_duplicate:
	@g++ -g -o neetcode_Q2/contains_duplicate neetcode_Q2/contains_duplicate.cpp
	@./neetcode_Q2/contains_duplicate

Valild_Anagram:
	@g++ -g -o neetcode_Q3/Valid_Anagram neetcode_Q3/Valid_Anagram.cpp
	@./neetcode_Q3/Valid_Anagram
