is_palindrome:
	@g++ -g -o neetcode_Q1/is_palindrome neetcode_Q1/is_palindrome.cpp
	@./neetcode_Q1/is_palindrome

contains_duplicate:
	@g++ -g -o neetcode_Q2/contains_duplicate neetcode_Q2/contains_duplicate.cpp
	@./neetcode_Q2/contains_duplicate

Valild_Anagram:
	@g++ -g -o neetcode_Q3/Valid_Anagram neetcode_Q3/Valid_Anagram.cpp
	@./neetcode_Q3/Valid_Anagram

Two_sum:
	@g++ -g -o neetcode_Q4/Two_sum neetcode_Q4/Two_sum.cpp
	@./neetcode_Q4/Two_sum

groupAnagram:
	@g++ -g -o neetcode_Q5/groupAnagram neetcode_Q5/groupAnagram.cpp
	@./neetcode_Q5/groupAnagram

topKfrequent:
	@g++ -g -o neetcode_Q6/topKfrequent neetcode_Q6/topKfrequent.cpp
	@./neetcode_Q6/topKfrequent

encode:
	@g++ -g -o neetcode_Q7/encode_decode neetcode_Q7/encode_decode.cpp
	@./neetcode_Q7/encode_decode

productExceptSelf:
	@g++ -g -o neetcode_Q8/productExceptSelf neetcode_Q8/productExceptSelf.cpp
	@./neetcode_Q8/productExceptSelf

isValidSudoko:
	@g++ -g -o neetcode_Q9/productExceptSelf neetcode_Q9/isValidSudoko.cpp
	@./neetcode_Q9/isValidSudoko
